jobs:
  test-3.8-production:
    docker:
    - {image: python:3.8}
    environment: {COLUMNS: '160', COVER_PACKAGES: 'geometry,geometry.unittests.poses_test,geometry.subspaces,geometry.manifolds.torus01,geometry.subspaces.subspaces,geometry.manifolds.sphere,geometry.manifolds.tests.embedding_test,geometry.manifolds.todo.grassman,geometry.unittests,geometry.unittests.rotations_tests,geometry.manifolds.torus,geometry.utils.numpy_backport,geometry.distances.spherical,geometry.spheres,geometry.unittests.mds_test,geometry.rotations,geometry.procrustes,geometry.manifolds.matrix_linear_space,geometry.unittests.utils_test,geometry.manifolds.group,geometry.distances,geometry.manifolds.translation_group,geometry.distances.generic,geometry.manifolds.point_set,geometry.manifolds.tests.matrix_groups_tests,geometry.manifolds.todo.posdef_matrices,geometry.manifolds.special_euclidean_algebra,geometry.unittests.misc_tests,geometry.types,geometry.manifolds.differentiable_manifold,geometry.unittests.procrustes_test,geometry.utils,geometry.manifolds.matrix_lie_group,geometry.manifolds.matrix_lie_algebra,geometry.manifolds.tangent_bundle,geometry.manifolds.translation_algebra,geometry.manifolds.product_manifold,geometry.manifolds,geometry.manifolds.tests.checks_generation,geometry.manifolds.todo.orthogonal_group,geometry.unittests.distances_test,geometry.manifolds.euclidean,geometry.yaml_,geometry.unittests.spheres_tests,geometry.manifolds.manifold_embedding_propagation,geometry.manifolds.tests.manifold_tests,geometry.manifolds.square,geometry.manifolds.embedding_relations,geometry.manifolds.special_orthogonal_group,geometry.constants,geometry.manifolds.todo,geometry.basic_utils,geometry.manifolds.matrix_lie_group_tangent,geometry.unittests.quaternions_test,geometry.manifolds.exceptions,geometry.manifolds.tests.sphere_tests,geometry.manifolds.todo.moebius,geometry.manifolds.tests.pickling_tests,geometry.poses,geometry.manifolds.todo.stiefel,geometry.unittests.random_geometry_tests,geometry.unittests.uniform_dist_pvalue_paranoia,geometry,geometry.manifolds.manifold_relations,geometry.spheres_embedding,geometry.unittests.random_geometry_density_tests,geometry.mds_algos,geometry.poses_embedding,geometry.manifolds.special_orthogonal_algebra,geometry.tex,geometry.formatting,geometry.manifolds.special_euclidean_group,geometry.rotations_embedding,geometry.manifolds.tests,geometry.unittests.utils',
      PATH: /root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin,
      TEST_PACKAGES: geometry}
    steps:
    - checkout
    - run: {command: "mkdir -p  build-stats\nenv | tee  build-stats/env.txt\n", name: Build
          stats (1)}
    - store_artifacts: {destination: build-stats, path: build-stats}
    - run: {command: "pip3 install -U pip\npip3 install pipdeptree coverage shyaml\n\
          \nshyaml get-values install_requires < project.pp1.yaml > .requirements.txt\n\
          pip3 install  -r .requirements.txt\nrm .requirements.txt\n", name: Install
          deps}
    - run: {command: "shyaml get-values tests_require < project.pp1.yaml > .requirements_tests.txt\n\
          pip3 install -r .requirements_tests.txt\nrm .requirements_tests.txt\n\n\
          pip install \t\tpipdeptree==0.13.2\t\tbump2version\t\tnose==1.3.7\t\tnose2==0.10\t\
          \tnose2-html-report==0.6.0\t\tnose-parallel==0.4.0\t\tnose_xunitmp==0.4.1\t\
          \tpre-commit==2.11.1\t\trednose==1.3.0\t\tcoverage\tsphinx\t\tsphinx-rtd-theme\n",
        name: Install testing deps}
    - run: {command: "echo TERM = $TERM\n\npipdeptree | tee  build-stats/pipdeptree.txt\n\
          pip list   | tee  build-stats/pip-list.txt\npip freeze | tee  build-stats/pip-freeze.txt\n",
        name: Build stats (2)}
    - store_artifacts: {destination: build-stats, path: build-stats}
    - run: {command: "python setup.py develop --prefix ~/.local --no-deps\n", name: setup.py
          develop}
    - run: {command: "FILE=src/conf.py\nmkdir -p out/docs\nif test -f \"$FILE\"; then\n\
          \    sphinx-build src out/docs\nfi\n", name: Make docs}
    - store_artifacts: {destination: docs, path: out/docs, when: always}
    - run: {command: "mkdir -p out/test-results\nxunit_output=out/test-results/nose-${CIRCLE_NODE_INDEX}-xunit.xml\n\
          \n#              --processes=8 --process-timeout=1000 --process-restartworker\
          \ \\\n# --cover-packages=${COVER_PACKAGES} \\\nnosetests \\\n  --rednose\
          \ --immediate \\\n  --cover-tests --with-coverage \\\n  --with-xunitmp --xunitmp-file=${xunit_output}\
          \ \\\n  --cover-package=${COVER_PACKAGES} \\\n  ${TEST_PACKAGES}\n", name: Run
          tests}
    - store_test_results: {path: out/test-results, when: always}
    - run: {command: "coverage combine\ncoverage html -d out/coverage\ncoverage xml\n",
        name: Coverage report, when: always}
    - store_artifacts: {destination: coverage, path: out/coverage, when: always}
    - store_artifacts: {destination: tests, path: out/tests, when: always}
    - run: {command: "bash <(curl -s https://codecov.io/bash)\n", name: CodeCov, when: always}
    working_directory: ~/repo
  test-3.8-staging:
    docker:
    - {image: python:3.8}
    environment: {COLUMNS: '160', COVER_PACKAGES: 'geometry,geometry.unittests.poses_test,geometry.subspaces,geometry.manifolds.torus01,geometry.subspaces.subspaces,geometry.manifolds.sphere,geometry.manifolds.tests.embedding_test,geometry.manifolds.todo.grassman,geometry.unittests,geometry.unittests.rotations_tests,geometry.manifolds.torus,geometry.utils.numpy_backport,geometry.distances.spherical,geometry.spheres,geometry.unittests.mds_test,geometry.rotations,geometry.procrustes,geometry.manifolds.matrix_linear_space,geometry.unittests.utils_test,geometry.manifolds.group,geometry.distances,geometry.manifolds.translation_group,geometry.distances.generic,geometry.manifolds.point_set,geometry.manifolds.tests.matrix_groups_tests,geometry.manifolds.todo.posdef_matrices,geometry.manifolds.special_euclidean_algebra,geometry.unittests.misc_tests,geometry.types,geometry.manifolds.differentiable_manifold,geometry.unittests.procrustes_test,geometry.utils,geometry.manifolds.matrix_lie_group,geometry.manifolds.matrix_lie_algebra,geometry.manifolds.tangent_bundle,geometry.manifolds.translation_algebra,geometry.manifolds.product_manifold,geometry.manifolds,geometry.manifolds.tests.checks_generation,geometry.manifolds.todo.orthogonal_group,geometry.unittests.distances_test,geometry.manifolds.euclidean,geometry.yaml_,geometry.unittests.spheres_tests,geometry.manifolds.manifold_embedding_propagation,geometry.manifolds.tests.manifold_tests,geometry.manifolds.square,geometry.manifolds.embedding_relations,geometry.manifolds.special_orthogonal_group,geometry.constants,geometry.manifolds.todo,geometry.basic_utils,geometry.manifolds.matrix_lie_group_tangent,geometry.unittests.quaternions_test,geometry.manifolds.exceptions,geometry.manifolds.tests.sphere_tests,geometry.manifolds.todo.moebius,geometry.manifolds.tests.pickling_tests,geometry.poses,geometry.manifolds.todo.stiefel,geometry.unittests.random_geometry_tests,geometry.unittests.uniform_dist_pvalue_paranoia,geometry,geometry.manifolds.manifold_relations,geometry.spheres_embedding,geometry.unittests.random_geometry_density_tests,geometry.mds_algos,geometry.poses_embedding,geometry.manifolds.special_orthogonal_algebra,geometry.tex,geometry.formatting,geometry.manifolds.special_euclidean_group,geometry.rotations_embedding,geometry.manifolds.tests,geometry.unittests.utils',
      PATH: /root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin,
      TEST_PACKAGES: geometry}
    steps:
    - checkout
    - run: {command: "mkdir -p  build-stats\nenv | tee  build-stats/env.txt\n", name: Build
          stats (1)}
    - store_artifacts: {destination: build-stats, path: build-stats}
    - run: {command: "pip3 install -U pip\npip3 install pipdeptree coverage shyaml\n\
          \nshyaml get-values install_requires < project.pp1.yaml > .requirements.txt\n\
          pip3 install  -r .requirements.txt\nrm .requirements.txt\n", name: Install
          deps}
    - run: {command: "shyaml get-values tests_require < project.pp1.yaml > .requirements_tests.txt\n\
          pip3 install -r .requirements_tests.txt\nrm .requirements_tests.txt\n\n\
          pip install \t\tpipdeptree==0.13.2\t\tbump2version\t\tnose==1.3.7\t\tnose2==0.10\t\
          \tnose2-html-report==0.6.0\t\tnose-parallel==0.4.0\t\tnose_xunitmp==0.4.1\t\
          \tpre-commit==2.11.1\t\trednose==1.3.0\t\tcoverage\tsphinx\t\tsphinx-rtd-theme\n",
        name: Install testing deps}
    - run: {command: "echo TERM = $TERM\n\npipdeptree | tee  build-stats/pipdeptree.txt\n\
          pip list   | tee  build-stats/pip-list.txt\npip freeze | tee  build-stats/pip-freeze.txt\n",
        name: Build stats (2)}
    - store_artifacts: {destination: build-stats, path: build-stats}
    - run: {command: "python setup.py develop --prefix ~/.local --no-deps\n", name: setup.py
          develop}
    - run: {command: "FILE=src/conf.py\nmkdir -p out/docs\nif test -f \"$FILE\"; then\n\
          \    sphinx-build src out/docs\nfi\n", name: Make docs}
    - store_artifacts: {destination: docs, path: out/docs, when: always}
    - run: {command: "mkdir -p out/test-results\nxunit_output=out/test-results/nose-${CIRCLE_NODE_INDEX}-xunit.xml\n\
          \n#              --processes=8 --process-timeout=1000 --process-restartworker\
          \ \\\n# --cover-packages=${COVER_PACKAGES} \\\nnosetests \\\n  --rednose\
          \ --immediate \\\n  --cover-tests --with-coverage \\\n  --with-xunitmp --xunitmp-file=${xunit_output}\
          \ \\\n  --cover-package=${COVER_PACKAGES} \\\n  ${TEST_PACKAGES}\n", name: Run
          tests}
    - store_test_results: {path: out/test-results, when: always}
    - run: {command: "coverage combine\ncoverage html -d out/coverage\ncoverage xml\n",
        name: Coverage report, when: always}
    - store_artifacts: {destination: coverage, path: out/coverage, when: always}
    - store_artifacts: {destination: tests, path: out/tests, when: always}
    - run: {command: "bash <(curl -s https://codecov.io/bash)\n", name: CodeCov, when: always}
    working_directory: ~/repo
version: 2
workflows:
  test:
    jobs:
    - test-3.8-staging:
        context: pip-staging
        filters:
          branches: {only: /z7-stage.*/}
    - test-3.8-production:
        context: z7-production
        filters:
          branches: {ignore: /z7-stage.*/}
  version: 2

# sigil fcd7c546edc292dee39cf6e63d7b12e9
