version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.7
      - test-3.6
      - test-3.5
      - test-2.7
jobs:
  test-3.6: &test-template
    docker:
      - image: python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            pip install --user --upgrade -r requirements.txt
            python setup.py develop --prefix ~/.local --no-deps
            pip freeze

      - run:
          name: Run tests
          command: |
            pip install --user nose
            DISABLE_CONTRACTS=1 PATH=~/.local/bin:$PATH nosetests geometry
            PATH=~/.local/bin:$PATH nosetests geometry

  test-3.7:
      <<: *test-template
      docker:
      - image: python:3.7
  test-3.5:
    <<: *test-template
    docker:
      - image: python:3.5
  test-2.7:
    <<: *test-template
    docker:
      - image: python:2.7
